import { Customer, Project, Employee, Invoice, Notification, MonthlyRevenue } from './types';

export const mockCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Ahmed Al-Rashid',
    email: 'ahmed@alrashid.com',
    phone: '+966 55 123 4567',
    address: 'Riyadh, Al Olaya District',
    company: 'Al-Rashid Holdings',
    notes: 'Prefers walnut finishes. VIP client.',
    totalOrders: 8,
    totalSpent: 145000,
    createdAt: '2025-01-15',
    updatedAt: '2026-06-20',
  },
  {
    id: 'cust-2',
    name: 'Fatima Hassan',
    email: 'fatima.hassan@gmail.com',
    phone: '+966 54 987 6543',
    address: 'Jeddah, Al Hamra District',
    notes: 'Renovating a villa. Interested in custom interiors.',
    totalOrders: 3,
    totalSpent: 78000,
    createdAt: '2025-08-10',
    updatedAt: '2026-05-12',
  },
  {
    id: 'cust-3',
    name: 'Khalid Construction Co.',
    email: 'projects@khalidco.com',
    phone: '+966 53 456 7890',
    address: 'Dammam, Industrial Area',
    company: 'Khalid Construction',
    notes: 'Bulk aluminum window orders. Corporate account.',
    totalOrders: 15,
    totalSpent: 320000,
    createdAt: '2024-11-20',
    updatedAt: '2026-07-01',
  },
  {
    id: 'cust-4',
    name: 'Noura Interior Studio',
    email: 'hello@nourastudio.com',
    phone: '+966 56 234 5678',
    address: 'Riyadh, Al Malqa District',
    company: 'Noura Studio',
    notes: 'Frequent collaborator on interior design projects.',
    totalOrders: 12,
    totalSpent: 210000,
    createdAt: '2024-09-05',
    updatedAt: '2026-06-28',
  },
  {
    id: 'cust-5',
    name: 'Omar Bin Laden',
    email: 'omar.bl@outlook.com',
    phone: '+966 50 876 5432',
    address: 'Mecca, Al Aziziya District',
    notes: 'Custom kitchen cabinets and wardrobe project.',
    totalOrders: 2,
    totalSpent: 34000,
    createdAt: '2026-03-01',
    updatedAt: '2026-06-15',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Yusuf Ahmed',
    email: 'yusuf@kassahun.com',
    phone: '+966 55 111 2233',
    specialty: 'carpenter',
    division: 'wood',
    isActive: true,
    assignedProjects: 4,
    completedProjects: 23,
    joinedAt: '2023-06-15',
  },
  {
    id: 'emp-2',
    name: 'Hassan Omar',
    email: 'hassan@kassahun.com',
    phone: '+966 55 222 3344',
    specialty: 'aluminum_fabricator',
    division: 'aluminum',
    isActive: true,
    assignedProjects: 3,
    completedProjects: 18,
    joinedAt: '2023-09-01',
  },
  {
    id: 'emp-3',
    name: 'Leila Ibrahim',
    email: 'leila@kassahun.com',
    phone: '+966 55 333 4455',
    specialty: 'designer',
    division: 'interior_design',
    isActive: true,
    assignedProjects: 5,
    completedProjects: 15,
    joinedAt: '2024-01-10',
  },
  {
    id: 'emp-4',
    name: 'Ali Mahmoud',
    email: 'ali@kassahun.com',
    phone: '+966 55 444 5566',
    specialty: 'carpenter',
    division: 'wood',
    isActive: true,
    assignedProjects: 2,
    completedProjects: 31,
    joinedAt: '2022-11-20',
  },
  {
    id: 'emp-5',
    name: 'Tariq Sulaiman',
    email: 'tariq@kassahun.com',
    phone: '+966 55 555 6677',
    specialty: 'aluminum_fabricator',
    division: 'aluminum',
    isActive: true,
    assignedProjects: 3,
    completedProjects: 12,
    joinedAt: '2024-05-15',
  },
  {
    id: 'emp-6',
    name: 'Sara Hassan',
    email: 'sara@kassahun.com',
    phone: '+966 55 666 7788',
    specialty: 'designer',
    division: 'interior_design',
    isActive: false,
    assignedProjects: 0,
    completedProjects: 8,
    joinedAt: '2025-02-01',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Custom Walnut Dining Set',
    description: '8-seat dining table with matching chairs in American walnut.',
    jobId: 'WD-1024',
    customerId: 'cust-1',
    customerName: 'Ahmed Al-Rashid',
    division: 'wood',
    jobCategory: 'furniture',
    status: 'in_progress',
    priority: 'high',
    assignedTo: ['emp-1', 'emp-4'],
    assignedEmployees: ['Yusuf Ahmed', 'Ali Mahmoud'],
    materials: [
      {
        id: 'mat-1',
        projectId: 'proj-1',
        type: 'wood',
        name: 'American Walnut',
        species: 'Juglans nigra',
        finish: 'Natural oil',
        swatchColor: '#5C3A21',
        notes: 'Quarter-sawn, kiln dried',
        selectedBy: 'Leila Ibrahim',
        selectedAt: '2026-06-15',
      },
      {
        id: 'mat-2',
        projectId: 'proj-1',
        type: 'hardware',
        name: 'Brass Table Legs',
        color: '#B8860B',
        swatchColor: '#B8860B',
        notes: 'Hand-forged tapered legs',
        selectedBy: 'Leila Ibrahim',
        selectedAt: '2026-06-15',
      },
    ],
    photos: [],
    drawings: [],
    estimatedCost: 45000,
    finalCost: 0,
    deposit: 15000,
    startDate: '2026-06-20',
    dueDate: '2026-07-20',
    createdAt: '2026-06-10',
    updatedAt: '2026-07-01',
  },
  {
    id: 'proj-2',
    title: 'Aluminum Sliding Windows — Villa',
    description: '12 sliding windows with thermal break aluminum profiles for a villa renovation.',
    jobId: 'AL-3012',
    customerId: 'cust-3',
    customerName: 'Khalid Construction Co.',
    division: 'aluminum',
    jobCategory: 'aluminum_fabrication',
    status: 'completed',
    priority: 'medium',
    assignedTo: ['emp-2', 'emp-5'],
    assignedEmployees: ['Hassan Omar', 'Tariq Sulaiman'],
    materials: [
      {
        id: 'mat-3',
        projectId: 'proj-2',
        type: 'aluminum',
        name: 'Thermal Break Profile 780',
        profile: 'Series 780',
        color: 'Anthracite Grey',
        swatchColor: '#505050',
        notes: 'Powder coated, 78mm depth',
        selectedBy: 'Leila Ibrahim',
        selectedAt: '2026-05-20',
      },
    ],
    photos: [],
    drawings: [],
    estimatedCost: 82000,
    finalCost: 82000,
    deposit: 41000,
    startDate: '2026-05-25',
    dueDate: '2026-06-30',
    completedDate: '2026-06-28',
    deliveredDate: '2026-07-01',
    createdAt: '2026-05-15',
    updatedAt: '2026-07-01',
  },
  {
    id: 'proj-3',
    title: 'Living Room Interior Redesign',
    description: 'Full interior redesign including custom furniture, lighting, and decor.',
    jobId: 'DS-2008',
    customerId: 'cust-2',
    customerName: 'Fatima Hassan',
    division: 'interior_design',
    jobCategory: 'interior_design_consulting',
    status: 'new',
    priority: 'high',
    assignedTo: ['emp-3'],
    assignedEmployees: ['Leila Ibrahim'],
    materials: [],
    photos: [],
    drawings: [],
    estimatedCost: 120000,
    finalCost: 0,
    deposit: 0,
    startDate: '2026-07-10',
    dueDate: '2026-09-15',
    createdAt: '2026-07-02',
    updatedAt: '2026-07-02',
  },
  {
    id: 'proj-4',
    title: 'Office Partitions — Aluminum & Glass',
    description: 'Aluminum partition system with tempered glass panels for office space.',
    jobId: 'AL-3015',
    customerId: 'cust-3',
    customerName: 'Khalid Construction Co.',
    division: 'aluminum',
    jobCategory: 'aluminum_fabrication',
    status: 'in_progress',
    priority: 'medium',
    assignedTo: ['emp-2'],
    assignedEmployees: ['Hassan Omar'],
    materials: [
      {
        id: 'mat-4',
        projectId: 'proj-4',
        type: 'aluminum',
        name: 'Silver Anodized Profile',
        profile: 'Series 520',
        color: 'Silver Anodized',
        swatchColor: '#C0C0C0',
        notes: 'Standard anodized finish',
        selectedBy: 'Hassan Omar',
        selectedAt: '2026-06-25',
      },
    ],
    photos: [],
    drawings: [],
    estimatedCost: 55000,
    finalCost: 0,
    deposit: 20000,
    startDate: '2026-06-28',
    dueDate: '2026-07-25',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-30',
  },
  {
    id: 'proj-5',
    title: 'Custom Kitchen Cabinets',
    description: 'Modern kitchen cabinets in oak with soft-close hardware.',
    jobId: 'WD-1030',
    customerId: 'cust-5',
    customerName: 'Omar Bin Laden',
    division: 'wood',
    jobCategory: 'furniture',
    status: 'delivered',
    priority: 'medium',
    assignedTo: ['emp-1'],
    assignedEmployees: ['Yusuf Ahmed'],
    materials: [
      {
        id: 'mat-5',
        projectId: 'proj-5',
        type: 'wood',
        name: 'European Oak',
        species: 'Quercus robur',
        finish: 'Matte lacquer',
        swatchColor: '#C4A35A',
        notes: 'Rift-cut, 40mm panels',
        selectedBy: 'Yusuf Ahmed',
        selectedAt: '2026-05-10',
      },
    ],
    photos: [],
    drawings: [],
    estimatedCost: 38000,
    finalCost: 38000,
    deposit: 19000,
    startDate: '2026-05-15',
    dueDate: '2026-06-15',
    completedDate: '2026-06-12',
    deliveredDate: '2026-06-18',
    createdAt: '2026-05-01',
    updatedAt: '2026-06-18',
  },
  {
    id: 'proj-6',
    title: 'Bedroom Wardrobe Set',
    description: 'Custom 4-door wardrobe with internal organizer system.',
    jobId: 'WD-1032',
    customerId: 'cust-4',
    customerName: 'Noura Interior Studio',
    division: 'wood',
    jobCategory: 'furniture',
    status: 'new',
    priority: 'low',
    assignedTo: ['emp-4'],
    assignedEmployees: ['Ali Mahmoud'],
    materials: [],
    photos: [],
    drawings: [],
    estimatedCost: 28000,
    finalCost: 0,
    deposit: 0,
    startDate: '2026-07-15',
    dueDate: '2026-08-20',
    createdAt: '2026-07-01',
    updatedAt: '2026-07-01',
  },
  {
    id: 'proj-7',
    title: 'Aluminum Railing System',
    description: 'Balcony railing with tempered glass and aluminum frame.',
    jobId: 'AL-3018',
    customerId: 'cust-1',
    customerName: 'Ahmed Al-Rashid',
    division: 'aluminum',
    jobCategory: 'aluminum_fabrication',
    status: 'paid',
    priority: 'low',
    assignedTo: ['emp-5'],
    assignedEmployees: ['Tariq Sulaiman'],
    materials: [
      {
        id: 'mat-6',
        projectId: 'proj-7',
        type: 'aluminum',
        name: 'Matte Black Profile',
        profile: 'Series 650',
        color: 'Matte Black',
        swatchColor: '#2A2A2E',
        notes: 'Powder coated matte black',
        selectedBy: 'Tariq Sulaiman',
        selectedAt: '2026-04-15',
      },
    ],
    photos: [],
    drawings: [],
    estimatedCost: 42000,
    finalCost: 42000,
    deposit: 21000,
    startDate: '2026-04-20',
    dueDate: '2026-05-20',
    completedDate: '2026-05-18',
    deliveredDate: '2026-05-22',
    createdAt: '2026-04-10',
    updatedAt: '2026-06-01',
  },
  {
    id: 'proj-8',
    title: 'Showroom Interior Fit-Out',
    description: 'Complete interior fit-out for furniture showroom display area.',
    jobId: 'DS-2012',
    customerId: 'cust-4',
    customerName: 'Noura Interior Studio',
    division: 'interior_design',
    jobCategory: 'interior_design_consulting',
    status: 'in_progress',
    priority: 'high',
    assignedTo: ['emp-3', 'emp-1'],
    assignedEmployees: ['Leila Ibrahim', 'Yusuf Ahmed'],
    materials: [],
    photos: [],
    drawings: [],
    estimatedCost: 180000,
    finalCost: 0,
    deposit: 60000,
    startDate: '2026-06-01',
    dueDate: '2026-08-15',
    createdAt: '2026-05-20',
    updatedAt: '2026-06-28',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    projectId: 'proj-2',
    projectTitle: 'Aluminum Sliding Windows — Villa',
    customerId: 'cust-3',
    customerName: 'Khalid Construction Co.',
    invoiceNumber: 'INV-10001',
    items: [
      { id: 'item-1', description: 'Aluminum sliding windows (12 units)', category: 'material', quantity: 12, unitPrice: 4500, total: 54000 },
      { id: 'item-2', description: 'Installation labor', category: 'labor', quantity: 1, unitPrice: 18000, total: 18000 },
      { id: 'item-3', description: 'Thermal break upgrade', category: 'material', quantity: 12, unitPrice: 500, total: 6000 },
      { id: 'item-4', description: 'Delivery & transport', category: 'delivery', quantity: 1, unitPrice: 4000, total: 4000 },
    ],
    subtotal: 82000,
    vatRate: 15,
    vatAmount: 12300,
    total: 94300,
    amountPaid: 94300,
    balanceDue: 0,
    paymentMethod: 'bank_transfer',
    paymentDate: '2026-07-01',
    status: 'paid',
    dueDate: '2026-07-15',
    createdAt: '2026-06-30',
  },
  {
    id: 'inv-2',
    projectId: 'proj-5',
    projectTitle: 'Custom Kitchen Cabinets',
    customerId: 'cust-5',
    customerName: 'Omar Bin Laden',
    invoiceNumber: 'INV-10002',
    items: [
      { id: 'item-5', description: 'Kitchen cabinets — European Oak', category: 'material', quantity: 1, unitPrice: 22000, total: 22000 },
      { id: 'item-6', description: 'Carpentry labor', category: 'labor', quantity: 1, unitPrice: 12000, total: 12000 },
      { id: 'item-7', description: 'Soft-close hardware', category: 'material', quantity: 1, unitPrice: 2500, total: 2500 },
      { id: 'item-8', description: 'Installation', category: 'labor', quantity: 1, unitPrice: 3500, total: 3500 },
    ],
    subtotal: 40000,
    vatRate: 15,
    vatAmount: 6000,
    total: 46000,
    amountPaid: 19000,
    balanceDue: 27000,
    status: 'sent',
    dueDate: '2026-07-18',
    createdAt: '2026-06-18',
  },
  {
    id: 'inv-3',
    projectId: 'proj-7',
    projectTitle: 'Aluminum Railing System',
    customerId: 'cust-1',
    customerName: 'Ahmed Al-Rashid',
    invoiceNumber: 'INV-10003',
    items: [
      { id: 'item-9', description: 'Aluminum railing system — matte black', category: 'material', quantity: 1, unitPrice: 25000, total: 25000 },
      { id: 'item-10', description: 'Tempered glass panels', category: 'material', quantity: 8, unitPrice: 1200, total: 9600 },
      { id: 'item-11', description: 'Installation labor', category: 'labor', quantity: 1, unitPrice: 7400, total: 7400 },
    ],
    subtotal: 42000,
    vatRate: 15,
    vatAmount: 6300,
    total: 48300,
    amountPaid: 48300,
    balanceDue: 0,
    paymentMethod: 'cash',
    paymentDate: '2026-06-01',
    status: 'paid',
    dueDate: '2026-06-15',
    createdAt: '2026-05-22',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'order_completed',
    title: 'Project Completed',
    message: 'Aluminum Sliding Windows — Villa has been marked as completed.',
    read: false,
    projectId: 'proj-2',
    createdAt: '2026-06-28T14:30:00',
  },
  {
    id: 'notif-2',
    type: 'overdue',
    title: 'Overdue Alert',
    message: 'Office Partitions — Aluminum & Glass is approaching its due date.',
    read: false,
    projectId: 'proj-4',
    createdAt: '2026-07-01T09:00:00',
  },
  {
    id: 'notif-3',
    type: 'payment_received',
    title: 'Payment Received',
    message: 'SAR 48,300 received from Ahmed Al-Rashid for INV-10003.',
    read: true,
    projectId: 'proj-7',
    createdAt: '2026-06-01T11:15:00',
  },
  {
    id: 'notif-4',
    type: 'new_order',
    title: 'New Work Order',
    message: 'New project "Living Room Interior Redesign" created for Fatima Hassan.',
    read: true,
    projectId: 'proj-3',
    createdAt: '2026-07-02T10:00:00',
  },
  {
    id: 'notif-5',
    type: 'material_selected',
    title: 'Material Selected',
    message: 'American Walnut selected for Custom Walnut Dining Set.',
    read: true,
    projectId: 'proj-1',
    createdAt: '2026-06-15T16:45:00',
  },
  {
    id: 'notif-6',
    type: 'assignment',
    title: 'New Assignment',
    message: 'You have been assigned to Showroom Interior Fit-Out.',
    read: false,
    projectId: 'proj-8',
    createdAt: '2026-06-01T08:00:00',
  },
];

export const mockMonthlyRevenue: MonthlyRevenue[] = [
  { month: 'Jan', wood: 45000, aluminum: 32000, design: 15000, total: 92000 },
  { month: 'Feb', wood: 38000, aluminum: 28000, design: 22000, total: 88000 },
  { month: 'Mar', wood: 52000, aluminum: 45000, design: 18000, total: 115000 },
  { month: 'Apr', wood: 61000, aluminum: 38000, design: 25000, total: 124000 },
  { month: 'May', wood: 48000, aluminum: 52000, design: 30000, total: 130000 },
  { month: 'Jun', wood: 55000, aluminum: 41000, design: 28000, total: 124000 },
  { month: 'Jul', wood: 35000, aluminum: 25000, design: 20000, total: 80000 },
];
